version: 0.9.6.{build}
test_script:
- nunit-console.exe Mono.Cecil.nunit
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/925de8a68a6d8d3ce68e
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
image: Visual Studio 2017
install:
- cmd: appveyor downloadfile https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe
build_script:
- ps: >-
    dotnet restore

    dotnet clean Mono.Cecil.sln

    dotnet build Mono.Cecil.sln /verbosity:quiet /p:Configuration=net_3_5_Release

    dotnet clean Mono.Cecil.sln

    dotnet build Mono.Cecil.sln /verbosity:quiet /p:Configuration=net_4_0_Release

    dotnet clean Mono.Cecil.sln

    dotnet build Mono.Cecil.sln /verbosity:quiet /p:Configuration=netstandard_Release


    dotnet clean Mono.Cecil.sln

    dotnet build Mono.Cecil.sln /verbosity:quiet /p:Configuration=net_3_5_Release_ReadOnly
    
    dotnet clean Mono.Cecil.sln

    dotnet build Mono.Cecil.sln /verbosity:quiet /p:Configuration=net_4_0_Release_ReadOnly

    dotnet clean Mono.Cecil.sln

    dotnet build Mono.Cecil.sln /verbosity:quiet /p:Configuration=netstandard_Release_ReadOnly


    7z a all.zip -r bin\
artifacts:
- path: bin/**/*.dll
- path: bin/**/*.pdb
- path: all.zip