version: 0.9.6.{build}
test_script:
- ps: >-
    nunit-console.exe Mono.Cecil.nunit

    dotnet test "Test\Mono.Cecil.Tests.csproj" --framework netcoreapp2.0 --configuration netstandard_Release --no-build --output bin\netstandard_Release\netcoreapp2.0 | Out-Null
    dotnet test "Test\Mono.Cecil.Tests.csproj" --framework netcoreapp2.0 --configuration netstandard_Release_ReadOnly --no-build --output bin\netstandard_Release_ReadOnly\netcoreapp2.0 | Out-Null
    dotnet test "rocks\Test\Mono.Cecil.Rocks.Tests.csproj" --framework netcoreapp2.0 --configuration netstandard_Release --no-build --output bin\netstandard_Release\netcoreapp2.0 | Out-Null
    dotnet test "rocks\Test\Mono.Cecil.Rocks.Tests.csproj" --framework netcoreapp2.0 --configuration netstandard_Release_ReadOnly --no-build --output bin\netstandard_Release_ReadOnly\netcoreapp2.0 | Out-Null
    dotnet test "symbols\mdb\Test\Mono.Cecil.Mdb.Tests.csproj" --framework netcoreapp2.0 --configuration netstandard_Release --no-build --output bin\netstandard_Release\netcoreapp2.0 | Out-Null
    dotnet test "symbols\mdb\Test\Mono.Cecil.Mdb.Tests.csproj" --framework netcoreapp2.0 --configuration netstandard_Release_ReadOnly --no-build --output bin\netstandard_Release_ReadOnly\netcoreapp2.0 | Out-Null
    dotnet test "symbols\pdb\Test\Mono.Cecil.Pdb.Tests.csproj" --framework netcoreapp2.0 --configuration netstandard_Release --no-build --output bin\netstandard_Release\netcoreapp2.0 | Out-Null
    dotnet test "symbols\pdb\Test\Mono.Cecil.Pdb.Tests.csproj" --framework netcoreapp2.0 --configuration netstandard_Release_ReadOnly --no-build --output bin\netstandard_Release_ReadOnly\netcoreapp2.0 | Out-Null
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/925de8a68a6d8d3ce68e
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
image: Visual Studio 2017
install:
- cmd: appveyor downloadfile https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe
build_script:
- ps: >-
    dotnet restore | Out-Null

    dotnet clean Mono.Cecil.sln | Out-Null

    dotnet build Mono.Cecil.sln /verbosity:quiet /p:Configuration=net_3_5_Release | Out-Null

    dotnet clean Mono.Cecil.sln | Out-Null

    dotnet build Mono.Cecil.sln /verbosity:quiet /p:Configuration=net_4_0_Release | Out-Null

    dotnet clean Mono.Cecil.sln | Out-Null

    dotnet build Mono.Cecil.sln /verbosity:quiet /p:Configuration=netstandard_Release | Out-Null


    dotnet clean Mono.Cecil.sln | Out-Null

    dotnet build Mono.Cecil.sln /verbosity:quiet /p:Configuration=net_3_5_Release_ReadOnly | Out-Null

    dotnet clean Mono.Cecil.sln | Out-Null

    dotnet build Mono.Cecil.sln /verbosity:quiet /p:Configuration=net_4_0_Release_ReadOnly | Out-Null

    dotnet clean Mono.Cecil.sln | Out-Null

    dotnet build Mono.Cecil.sln /verbosity:quiet /p:Configuration=netstandard_Release_ReadOnly | Out-Null


    7z a all.zip -r bin\
artifacts:
- path: bin/**/*.dll
- path: bin/**/*.pdb
- path: all.zip